nodeLinker: node-modules


npmScopes:
  open-mercato:
    npmRegistryServer: "http://localhost:4873"
    npmAlwaysAuth: true
    npmAuthToken: "ODU0MGFkYjQwOTcyMzFjMWRmYjU3YWRhMmJmNjEyMDg6YmE1MDI4NzIyNGNiMGNmMWFi"
